/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeleteEntityRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-27T19:03:42.962Z")
public class DeleteEntityRequest {
  @SerializedName("type")
  private String type = null;

  @SerializedName("entity")
  private Object entity = null;

  public DeleteEntityRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Canonical name of entity class type in package format ex. com.onyx.my.EntityName
   * @return type
  **/
  @ApiModelProperty(value = "Canonical name of entity class type in package format ex. com.onyx.my.EntityName")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DeleteEntityRequest entity(Object entity) {
    this.entity = entity;
    return this;
  }

   /**
   * JSON Representation of Managed Entity
   * @return entity
  **/
  @ApiModelProperty(value = "JSON Representation of Managed Entity")
  public Object getEntity() {
    return entity;
  }

  public void setEntity(Object entity) {
    this.entity = entity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteEntityRequest deleteEntityRequest = (DeleteEntityRequest) o;
    return Objects.equals(this.type, deleteEntityRequest.type) &&
        Objects.equals(this.entity, deleteEntityRequest.entity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, entity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteEntityRequest {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

