/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FindRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-27T19:03:42.962Z")
public class FindRequest {
  @SerializedName("id")
  private Object id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("partitionValue")
  private Object partitionValue = null;

  public FindRequest id(Object id) {
    this.id = id;
    return this;
  }

   /**
   * Entity&#39;s identifier value
   * @return id
  **/
  @ApiModelProperty(value = "Entity's identifier value")
  public Object getId() {
    return id;
  }

  public void setId(Object id) {
    this.id = id;
  }

  public FindRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Entity Type in package format ex.  com.onyx.my.EntityName
   * @return type
  **/
  @ApiModelProperty(value = "Entity Type in package format ex.  com.onyx.my.EntityName")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FindRequest partitionValue(Object partitionValue) {
    this.partitionValue = partitionValue;
    return this;
  }

   /**
   * Partition Value that the managed entity belongs to (optional)
   * @return partitionValue
  **/
  @ApiModelProperty(value = "Partition Value that the managed entity belongs to (optional)")
  public Object getPartitionValue() {
    return partitionValue;
  }

  public void setPartitionValue(Object partitionValue) {
    this.partitionValue = partitionValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindRequest findRequest = (FindRequest) o;
    return Objects.equals(this.id, findRequest.id) &&
        Objects.equals(this.type, findRequest.type) &&
        Objects.equals(this.partitionValue, findRequest.partitionValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, partitionValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindRequest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    partitionValue: ").append(toIndentedString(partitionValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

