/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InitializeRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-27T19:03:42.962Z")
public class InitializeRequest {
  @SerializedName("entityId")
  private Object entityId = null;

  @SerializedName("attribute")
  private String attribute = null;

  @SerializedName("entityType")
  private String entityType = null;

  @SerializedName("partitionId")
  private Object partitionId = null;

  public InitializeRequest entityId(Object entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Entity Primary Key
   * @return entityId
  **/
  @ApiModelProperty(value = "Entity Primary Key")
  public Object getEntityId() {
    return entityId;
  }

  public void setEntityId(Object entityId) {
    this.entityId = entityId;
  }

  public InitializeRequest attribute(String attribute) {
    this.attribute = attribute;
    return this;
  }

   /**
   * Relationship property name
   * @return attribute
  **/
  @ApiModelProperty(value = "Relationship property name")
  public String getAttribute() {
    return attribute;
  }

  public void setAttribute(String attribute) {
    this.attribute = attribute;
  }

  public InitializeRequest entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Relationship entity class type in package.format e.x com.onyx.entity.MyEntity
   * @return entityType
  **/
  @ApiModelProperty(value = "Relationship entity class type in package.format e.x com.onyx.entity.MyEntity")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public InitializeRequest partitionId(Object partitionId) {
    this.partitionId = partitionId;
    return this;
  }

   /**
   * Partition Value(optional)
   * @return partitionId
  **/
  @ApiModelProperty(value = "Partition Value(optional)")
  public Object getPartitionId() {
    return partitionId;
  }

  public void setPartitionId(Object partitionId) {
    this.partitionId = partitionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitializeRequest initializeRequest = (InitializeRequest) o;
    return Objects.equals(this.entityId, initializeRequest.entityId) &&
        Objects.equals(this.attribute, initializeRequest.attribute) &&
        Objects.equals(this.entityType, initializeRequest.entityType) &&
        Objects.equals(this.partitionId, initializeRequest.partitionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, attribute, entityType, partitionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitializeRequest {\n");
    
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    partitionId: ").append(toIndentedString(partitionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

