/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Query criteria operator
 */
@JsonAdapter(QueryCriteriaOperator.Adapter.class)
public enum QueryCriteriaOperator {
  
  EQUAL("EQUAL"),
  
  NOT_EQUAL("NOT_EQUAL"),
  
  NOT_STARTS_WITH("NOT_STARTS_WITH"),
  
  NOT_NULL("NOT_NULL"),
  
  IS_NULL("IS_NULL"),
  
  STARTS_WITH("STARTS_WITH"),
  
  CONTAINS("CONTAINS"),
  
  NOT_CONTAINS("NOT_CONTAINS"),
  
  LIKE("LIKE"),
  
  NOT_LIKE("NOT_LIKE"),
  
  MATCHES("MATCHES"),
  
  NOT_MATCHES("NOT_MATCHES"),
  
  LESS_THAN("LESS_THAN"),
  
  GREATER_THAN("GREATER_THAN"),
  
  LESS_THAN_EQUAL("LESS_THAN_EQUAL"),
  
  GREATER_THAN_EQUAL("GREATER_THAN_EQUAL"),
  
  IN("IN"),
  
  NOT_IN("NOT_IN");

  private String value;

  QueryCriteriaOperator(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static QueryCriteriaOperator fromValue(String text) {
    for (QueryCriteriaOperator b : QueryCriteriaOperator.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<QueryCriteriaOperator> {
    @Override
    public void write(final JsonWriter jsonWriter, final QueryCriteriaOperator enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public QueryCriteriaOperator read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return QueryCriteriaOperator.fromValue(String.valueOf(value));
    }
  }
}

