/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * QueryOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-27T19:03:42.962Z")
public class QueryOrder {
  @SerializedName("attribute")
  private String attribute = null;

  @SerializedName("isAscending")
  private Boolean isAscending = null;

  public QueryOrder attribute(String attribute) {
    this.attribute = attribute;
    return this;
  }

   /**
   * Attribute to order by
   * @return attribute
  **/
  @ApiModelProperty(value = "Attribute to order by")
  public String getAttribute() {
    return attribute;
  }

  public void setAttribute(String attribute) {
    this.attribute = attribute;
  }

  public QueryOrder isAscending(Boolean isAscending) {
    this.isAscending = isAscending;
    return this;
  }

   /**
   * Ascending or descending
   * @return isAscending
  **/
  @ApiModelProperty(value = "Ascending or descending")
  public Boolean getIsAscending() {
    return isAscending;
  }

  public void setIsAscending(Boolean isAscending) {
    this.isAscending = isAscending;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryOrder queryOrder = (QueryOrder) o;
    return Objects.equals(this.attribute, queryOrder.attribute) &&
        Objects.equals(this.isAscending, queryOrder.isAscending);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attribute, isAscending);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryOrder {\n");
    
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("    isAscending: ").append(toIndentedString(isAscending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

