/*
 * Onyx Persistence API
 * Access your database via Web Services
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ManagedEntity;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SaveEntitiesRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-27T19:03:42.962Z")
public class SaveEntitiesRequest {
  @SerializedName("type")
  private String type = null;

  @SerializedName("entities")
  private List<ManagedEntity> entities = null;

  public SaveEntitiesRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of entities to save.  This contains the entity type&#39;s canonical name.
   * @return type
  **/
  @ApiModelProperty(value = "Type of entities to save.  This contains the entity type's canonical name.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SaveEntitiesRequest entities(List<ManagedEntity> entities) {
    this.entities = entities;
    return this;
  }

  public SaveEntitiesRequest addEntitiesItem(ManagedEntity entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<ManagedEntity>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * Entities to persist
   * @return entities
  **/
  @ApiModelProperty(value = "Entities to persist")
  public List<ManagedEntity> getEntities() {
    return entities;
  }

  public void setEntities(List<ManagedEntity> entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveEntitiesRequest saveEntitiesRequest = (SaveEntitiesRequest) o;
    return Objects.equals(this.type, saveEntitiesRequest.type) &&
        Objects.equals(this.entities, saveEntitiesRequest.entities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, entities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveEntitiesRequest {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

