/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.onyx.java-conventions")
    kotlin("jvm") version Config.KOTLIN_VERSION
}

dependencies {
    implementation(project(":onyx-database"))
    implementation(project(":onyx-remote-database"))
    implementation(project(":onyx-remote-driver"))
    implementation(project(":onyx-lucene-index"))
    implementation(project(":onyx-faiss-index"))
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:${Config.KOTLIN_VERSION}")
    testImplementation(kotlin("test"))
}

description = "dev.onyx:onyx-database-tests"

tasks.getByName<Test>("test") {
    useJUnit()
    minHeapSize = "2048m"
    maxHeapSize = "4096m"
}

project.tasks.publish.configure {
    this.enabled = false
}

java {
    withJavadocJar()
}

kotlin {
    jvmToolchain(Config.JAVA_VERSION)
}
