/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "onyx-database-parent"
include(":onyx-database")
include(":onyx-remote-database")
include(":onyx-remote-driver")
include(":onyx-web-database")
include(":onyx-database-tests")
