plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "onyx-database-parent"
include(":onyx-database")
include(":onyx-remote-database")
include(":onyx-remote-driver")
include(":onyx-web-database")
include(":onyx-database-tests")
include(":onyx-ai")
include(":onyx-cloud-client")
