/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("dev.onyx.java-conventions")
    kotlin("jvm") version Config.KOTLIN_VERSION
}

dependencies {
    implementation(project(":onyx-database"))
    implementation(platform("io.ktor:ktor-bom:${Config.KTOR_VERSION}"))

    // Core dependencies
    implementation("io.ktor:ktor-client-core")
    implementation("io.ktor:ktor-client-cio") // Use CIO engine for HTTP and WebSocket support
    implementation("io.ktor:ktor-server-core:${Config.KTOR_VERSION}")
    implementation("io.ktor:ktor-server-netty:${Config.KTOR_VERSION}")
    implementation("io.ktor:ktor-server-websockets:${Config.KTOR_VERSION}")

    // WebSockets feature
    implementation("io.ktor:ktor-client-websockets")

    // Serialization (if needed)
    implementation("io.ktor:ktor-client-serialization")

    // Logging (optional, for debugging)
    implementation("io.ktor:ktor-client-logging")
}

description = "dev.onyx:onyx-remote-driver"

java {
    withJavadocJar()
}

kotlin {
    jvmToolchain(Config.JAVA_VERSION)
}
