/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.onyxdevtools.java-conventions")
    kotlin("jvm") version Config.KOTLIN_VERSION
}

description = "com.onyxdevtools:onyx-database"

java {
    withJavadocJar()
}
