/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.onyx.java-conventions")
    kotlin("jvm") version Config.KOTLIN_VERSION
}

description = "dev.onyx:onyx-database"

java {
    withJavadocJar()
}

kotlin {
    jvmToolchain(Config.JAVA_VERSION)
}
