package com.onyx.request.pojo;

/**
 * Created by timothy.osborn on 4/1/15.
 */
public enum RequestTokenType
{
    // Persistence
    PING,
    SAVE,
    BATCH_SAVE,
    DELETE,
    FIND,
    FIND_BY_ID,
    FIND_BY_ID_IN_PARTITION,
    EXISTS,
    EXISTS_IN_PARTITION,
    BATCH_DELETE,
    QUERY,
    QUERY_UPDATE,
    QUERY_DELETE,
    QUERY_LAZY,
    INITIALIZE,
    SAVE_RELATIONSHIPS,
    FIND_BY_REFERENCE_ID,
    FIND_WITH_PARTITION_ID,

    // Map
    MAP_PUT,
    MAP_GET,
    MAP_REMOVE,
    MAP_CLEAR,

    // Atomic Reference
    ATOMIC_PUT,
    ATOMIC_GET,
    ATOMIC_ADD_AND_GET,
    ATOMIC_GET_AND_ADD,

    // Re-entry Lock
    READ_LOCK,
    READ_TRY_LOCK,
    READ_UNLOCK,
    WRITE_LOCK,
    WRITE_UNLOCK,
    WRITE_TRY_LOCK,

    // File System
    FILE_MKDIR,
    FILE_MKDIRS,
    FILE_GET,
    FILE_GET_BY_ID,
    FILE_CREATE,
    FILE_DELETE,
    FILE_MOVE,
    FILE_EXIST,
    FILE_LIST,
    FILE_RELOAD,
    FILE_GET_CHECKSUM,

    // FILE
    FILE_INVALIDATE_CHUNK,
    FILE_GET_INVALID_CHUNKS,
    FILE_SET_INVALID_CHUNKS,
    FILE_GET_INVALID_NODES,
    FILE_GET_FILE_CHUNKS,
    FILE_ADD_CHUNK,
    FILE_WRITE,
    FILE_BROADCAST_WRITE,
    FILE_BROADCAST_ADD_CHUNK,
    FILE_BROADCAST_INVALIDATE_CHUNK,
    FILE_READ,
    FILE_TRUNCATE,
    FILE_FLUSH,
    FILE_GET_CHUNK_SIZE,


    // Invalidate cluster entry
    INVALIDATE,
    SYNCHRONIZE,
    REPLICATE,

    // Stream
    STREAM_CLASS,

    ;
}
