@file:Suppress("UnstableApiUsage")

import java.net.URI
import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    `java-library`
    `maven-publish`
    signing
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))
    testImplementation(kotlin("test"))
}

group = "dev.onyx"
version = Config.ONYX_VERSION
java.sourceCompatibility = Config.JAVA_TARGET
java.targetCompatibility = Config.JAVA_TARGET

java {
    withSourcesJar()
}

fun base64Decode(prop: String): String? {
    return project.findProperty(prop)?.let {
        String(Base64.getDecoder().decode(it.toString())).trim()
    }
}

signing {
    val secretKey = base64Decode("signing.secretKey")
    val password = project.findProperty("signing.password") as String?
    if (secretKey != null && password != null) {
        useInMemoryPgpKeys(secretKey, password)
        sign(publishing.publications)
    }
}

publishing {

    repositories {
        maven {
            url = URI("https://maven.pkg.github.com/OnyxDevTools/onyx-database-parent")
            val ossrhUsername = project.findProperty("ossrhUsername") as String?
            val ossrhPassword = project.findProperty("ossrhPassword") as String?
            if (ossrhUsername != null && ossrhPassword != null) {
                credentials {
                    username = ossrhUsername
                    password = ossrhPassword
                }
            }
        }
    }

    publications {
        publications.create<MavenPublication>("maven") {
            from(components["java"])
            val pub = this
            pom {
                name.set(pub.artifactId)
                description.set("Onyx Database is a graph database that is written in Kotlin and supports Java and Android.  It is designed to be lightweight and easy to use.  Features include in memory database, embedded, and remote server.  It leverages its own ORM and storage.")
                url.set("http://onyx.dev")
                licenses {
                    license {
                        name.set("Free Software Foundation's GNU AGPL v3.0")
                        url.set("https://www.gnu.org/licenses/agpl-3.0.en.html")
                    }
                }
                developers {
                    developer {
                        id.set("tosborn")
                        name.set("Tim Osborn")
                        email.set("tosborn@onyx.dev")
                    }
                }
                scm {
                    url.set("https://github.com/OnyxDevTools/onyx-database-parent")
                }
            }
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<GenerateModuleMetadata> {
    suppressedValidationErrors.add("enforced-platform")
}
