
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version Config.KOTLIN_VERSION
    id("dev.onyx.java-conventions")
}

dependencies {
    implementation(project(":onyx-database"))
    implementation(project(":onyx-remote-driver"))
    implementation("io.ktor:ktor-server-core:${Config.KTOR_VERSION}")
    implementation("io.ktor:ktor-server-netty:${Config.KTOR_VERSION}")
    implementation("io.ktor:ktor-server-websockets:${Config.KTOR_VERSION}")

}

description = "dev.onyx:onyx-remote-database"

java {
    withJavadocJar()
}

kotlin {
    jvmToolchain(Config.JAVA_VERSION)
}
